name: Maven Build and run Selenium Tests on Push

on:
  push:
    branches:
      - main
      - feature/*

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
#concurrency:
 # group: "pages"
  #cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: adopt

      - name: Cleanup Before Tests
        run : |
          rm -rf logs/ temp/

      - name: Install ChromeDriver
        run: |
          wget "https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          cd chromedriver-linux64
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin

      - name: Build and Run tests
        run: |
          echo "Running Selenium tests headlessly..."
          export RUN_HEADLESS=true
          mkdir target
          chmod a+w target
          mvn -B clean verify \
          -DskipTests=false \
          -Dcucumber.features=src/test/java/com/example/produktapi/features \
          -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver
          echo "Selenium tests completed."

 # deploy:
 #   environment:
 #     name: github-pages
 #     url: ${{ steps.deployment.outputs.page_url }}
 #   runs-on: ubuntu-latest
 #   steps:
 #     - name: Checkout
 #       uses: actions/checkout@v4
 #     - name: Setup Pages
 #       uses: actions/configure-pages@v5
 #     - name: Upload artifact
 #       uses: actions/upload-pages-artifact@v3
 #       with:
 #         path: './target/cucumber-reports.html'
 #    - name: Deploy to GitHub Pages
 #       id: deployment
 #       uses: actions/deploy-pages@v4