name: Maven Build and run Selenium Tests on Push

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: adopt

      - name: Install ChromeDriver
        run: |
          wget "https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          cd chromedriver-linux64
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin

      - name: Build and Run tests
        run: |
          echo "Running Selenium tests headlessly..."
          mvn -B clean verify \
          -DargLine="-Dheadless=true" \
          -DskipTests=false \
          -Dcucumber.features=src/test/java/com/example/produktapi/features \
          -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver
          echo "Selenium tests completed."
