name: Maven Build and Selenium Tests on Push

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: 22
          distribution: adopt

      - name: Install ChromeDriver
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/121.0.6167.184/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          cd chromedriver-linux64
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin

      - name: Build and Test with Maven
        run: mvn -B clean verify -DskipTests=false -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver